services:
  app:
    build: .
    container_name: skon
    ports:
      - "42069:42069"
    depends_on:
      - redis
    environment:
    - SKON_REDIS_ADDR="redis_db:6379"
    - SKON_REDIS_PASSWD=""
    - SKON_ALLOW_API="true"
    - SKON_ALLOW_SUGGEST="true"
    - SKON_DOMAIN=""
    volumes:
      - ./sample:/app/data/11.sample
    restart: unless-stopped

  redis:
    image: "redis:alpine"
    container_name: redis_db
    restart: unless-stopped
